apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 937129046285.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 937129046285.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 99c98544
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
