---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 937129046285.dkr.ecr.ap-northeast-2.amazonaws.com/nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
