---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: 937129046285.dkr.ecr.ap-northeast-2.amazonaws.com/rabbitmq:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5672
